version: "3"
services:
  px_dev_server:
    build:
      context: .
      dockerfile: ./docker/server/dev/Dockerfile
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./px/packages/pagexpress-server:/usr/src/app
      - ./docker/config:/usr/src/app/config
      - ./docker/server/px-config.js:/usr/src/app/px-config.js
      - px_dev_node_modules_server:/usr/src/app/node_modules
    env_file:
      - ./environment/env-dev
    depends_on:
      - px_dev_mongo
    networks:
      - px_dev
  px_dev_client:
    build:
      context: .
      dockerfile: ./docker/client/dev/Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./px/packages/pagexpress:/usr/src/app
      - px_dev_node_modules_client:/usr/src/app/node_modules
    env_file:
      - ./environment/env-dev
    depends_on:
      - px_dev_server
    networks:
      - px_dev
  px_dev_mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - px_dev_mongodb:/data/db
    networks:
      - px_dev
volumes:
  px_dev_mongodb:
  px_dev_node_modules_client:
  px_dev_node_modules_server:
networks:
  px_dev:
    driver: bridge
